// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE--5-eT1gK5hgCytWoSLOkGIlMZnoLxw',
    appId: '1:739367111519:web:c6fd9da0ae663e2139c4ea',
    messagingSenderId: '739367111519',
    projectId: 'citizenship-test-6c9ff',
    authDomain: 'citizenship-test-6c9ff.firebaseapp.com',
    storageBucket: 'citizenship-test-6c9ff.firebasestorage.app',
    measurementId: 'G-5F7XTL3MH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6G6wLQha7nxFl4qdEeMeJdFvaijRE6Zo',
    appId: '1:739367111519:android:0da43c62852d43e539c4ea',
    messagingSenderId: '739367111519',
    projectId: 'citizenship-test-6c9ff',
    storageBucket: 'citizenship-test-6c9ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF3RhwysbQDiEH3VbwXC2-o2A1bvfVgPQ',
    appId: '1:739367111519:ios:b79f494264e375fe39c4ea',
    messagingSenderId: '739367111519',
    projectId: 'citizenship-test-6c9ff',
    storageBucket: 'citizenship-test-6c9ff.firebasestorage.app',
    iosBundleId: 'com.example.exampro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF3RhwysbQDiEH3VbwXC2-o2A1bvfVgPQ',
    appId: '1:739367111519:ios:b79f494264e375fe39c4ea',
    messagingSenderId: '739367111519',
    projectId: 'citizenship-test-6c9ff',
    storageBucket: 'citizenship-test-6c9ff.firebasestorage.app',
    iosBundleId: 'com.example.exampro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE--5-eT1gK5hgCytWoSLOkGIlMZnoLxw',
    appId: '1:739367111519:web:68e1b9b31c7070f839c4ea',
    messagingSenderId: '739367111519',
    projectId: 'citizenship-test-6c9ff',
    authDomain: 'citizenship-test-6c9ff.firebaseapp.com',
    storageBucket: 'citizenship-test-6c9ff.firebasestorage.app',
    measurementId: 'G-VM38DJ295V',
  );
}
